package io.github.benas.jpopulator.randomizers;

import io.github.benas.jpopulator.api.Randomizer;

import static java.lang.String.valueOf;

/**
 * Randomizer that stringify values generated by a delegate {@link Randomizer}.
 *
 * @author Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 */
public class StringDelegatingRandomizer implements Randomizer<String> {

    private final Randomizer delegate;

    /**
     * Create a {@link StringDelegatingRandomizer}.
     *
     * @param delegate the delegate randomizer
     */
    public StringDelegatingRandomizer(final Randomizer delegate) {
        this.delegate = delegate;
    }

    @Override
    public String getRandomValue() {
        return valueOf(delegate.getRandomValue().toString());
    }
}
