/**
 * 
 */
package io.github.benas.jpopulator.randomizers;

import io.github.benas.jpopulator.api.Randomizer;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * A custom randomizer that generates a list of random values from another {@link Randomizer}
 * @author Eric Taix (eric.taix@gmail.com)
 */
public class ListRandomizer<T> implements Randomizer<List<T>> {

    private static final Random RANDOM = new Random();
    
	private Randomizer<T> elementRenadomizer;
	private int nb;
	
	/**
	 * Default constructor which will generate a list with a random number of element. Each element is generated by the {@link Randomizer} parameter 
	 * @param elementRandomizer
	 */
	public ListRandomizer(Randomizer<T> elementRandomizer) {
        this(elementRandomizer, (byte) Math.abs((Byte) (byte) (RANDOM.nextInt())));
	}
	
	/**
	 * Constructor which will generate a list with nb elements. Each element is generated by the {@link Randomizer} parameter 
	 * @param elementRandomizer The randomizer used to generate each element
	 * @param nb The number of elements in the list to generate
	 */
	public ListRandomizer(Randomizer<T> elementRandomizer, int nb) {
		this.elementRenadomizer = elementRandomizer;
		this.nb = nb;
	}
	
	@Override
	public List<T> getRandomValue() {
		List<T> result = new ArrayList<T>();
		for(int i = 0; i < nb; i++) {
			result.add(elementRenadomizer.getRandomValue());
		}
		return result;
	}

}
