/**
 * 
 */
package io.github.benas.jpopulator.randomizers;

import io.github.benas.jpopulator.api.Randomizer;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Random;

/**
 * A custom randomizer that generates a list of random values from another {@link Randomizer}
 * @author Eric Taix (eric.taix@gmail.com)
 */
public class ListRandomizer<T> implements Randomizer<Collection<T>> {

    private static final Random RANDOM = new Random();
    
	private Randomizer<T> elementRandomizer;
	private int min;
	private int max;
	
	/**
	 * Default constructor which will generate a list with a random number of element. Each element is generated by the {@link Randomizer} parameter 
	 * @param elementRandomizer
	 */
	public ListRandomizer(Randomizer<T> elementRandomizer) {
        this(elementRandomizer, 0, (byte) Math.abs((Byte) (byte) (RANDOM.nextInt())));
	}
	
	/**
	 * Constructor which will generate a list with a fixed nb of elements. Each element is generated by the {@link Randomizer} parameter 
	 * @param elementRandomizer The randomizer used to generate each element
	 * @param nb The number of elements in the list to generate
	 */
	public ListRandomizer(Randomizer<T> elementRandomizer, int nb) {
		this(elementRandomizer, nb, nb);
	}
	
	/**
	 * Constructor which will generate a list with a random nb of elements. Each element is generated by the {@link Randomizer} parameter 
	 * @param elementRandomizer The randomizer used to generate each element
	 * @param min The minimum number of elements in the list to generate
	 * @param max The maximum number of elements in the list to generate
	 */
	public ListRandomizer(Randomizer<T> elementRandomizer, int min, int max) {
		this.elementRandomizer = elementRandomizer;
		this.min = min;
		assert max >= min : "The maximum number of occurences should be higher or equal to the minimum number of occurrences.";
		this.max = max + 1;
	}
	
	@Override
	public Collection<T> getRandomValue() {
		List<T> result = new ArrayList<T>();
		int nb = RANDOM.nextInt(max-min) + min;
		for(int i = 0; i < nb; i++) {
			result.add(elementRandomizer.getRandomValue());
		}
		return result;
	}

}
