name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6.0.2
      - name: Set up JDK 17
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
      - name: Update release version
        run: ./mvnw versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.inputs.releaseVersion }}
      - name: Release to Maven Central
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./mvnw -Dgpg.keyname={{ secrets.GPG_KEY_ID }} --batch-mode --no-transfer-progress -s settings.xml -Prelease -Dmaven.test.skip=true deploy
